'use strict';
// 所有内容用 textContent 装配；外部 URL 仅允许 HTTPS，不执行内容中的 HTML。
let catalog; let feedback={items:{}}; let activeFilter='all'; let search=''; let timer;
const $=s=>document.querySelector(s);
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function link(text,href,cls){const a=el('a',cls,text);a.href=href;return a;}
function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:null;}catch{return null;}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
const kinds={hn:'每日精读',music:'每周歌单'};
function heading(title,sub){const wrap=el('div');const h=el('div','view-heading');h.append(el('h2','',title));wrap.append(h);if(sub)wrap.append(el('p','section-subtitle',sub));return wrap;}
function editionList(editions){const wrap=el('div','edition-list');for(const e of editions){const a=link('',`#edition/${e.id}`,'edition-link');a.append(el('span','edition-kind',e.kind==='hn'?'↗':'♫'));const copy=el('div');copy.append(el('p','edition-meta',`${e.date} · ${kinds[e.kind]} · ${e.items.length} ${e.kind==='hn'?'篇':'首'}`),el('h3','',e.title));a.append(copy,el('span','arrow','↗'));wrap.append(a);}return wrap;}
function empty(kind){const box=el('div','empty');const img=el('img');img.src='/mandy.svg';img.alt='';const text=el('div');text.append(el('h3','',kind==='music'?'下一首好歌，还在路上。':'新的书签，还在整理。'),el('p','',kind==='music'?'正式歌单会出现在这里。每周日香港时间 19:00 左右，计划更新。':'正式精读会出现在这里。每日香港时间 10:00，计划更新。'));text.append(link('先看看内容会长什么样 →',`#edition/sample-${kind}`,'sample-link'));box.append(img,text);return box;}
function privacy(){const box=el('div','reading');box.append(heading('关于这张云朵书桌','Dots 是 Mandy 整理公开阅读与音乐发现的地方。'));for(const [h,t] of [['内容与来源','精读保留来源、日期、正文与判断边界。歌单保留曲名、艺人、版本、推荐理由与官方链接。这里不发布个人完整音乐库、原始听歌记录、账户信息或内部笔记。'],['匿名反馈','点击反馈后，本浏览器会保存一个仅本站使用、90 天有效的随机匿名 Cookie，用来避免同一浏览器重复计票。点赞和点踩互斥，爱心可以单独选择，再点一次可撤回。它不验证身份，也不能阻止清理 Cookie 或换设备重复投票。'],['存储与防刷','服务器保存随机浏览器标识、条目编号、选择和最后更新时间，不存姓名、邮箱、原始 IP 或自由文本。网络地址仅用于内存中的短时限流。Cloudflare 和现有服务器访问日志仍按基础设施原有策略处理。公开接口只提供条目汇总，不公开浏览器标识或个人投票明细。'],['反馈如何被看见','反馈提交成功后立即持久化并更新计数；可见页面约每 30 秒刷新一次公共计数。它不会自动唤醒助手。后续整理时可读取累计反馈，但匿名热度不会被当成你的个人偏好。'],['不想保留反馈？','重新打开对应条目，点击已选反馈即可撤回。清理 Cookie 只移除浏览器识别，不能撤回此前服务器上的匿名选择。本站不做跨站身份关联。']]){box.append(el('h3','',h),el('p','prose',t));}return box;}
function reactionGroup(item){const row=el('div','reactions');row.setAttribute('aria-label',`对“${item.title}”的反馈`);for(const [type,icon,label] of [['up','👍','值得一读'],['down','👎','不太合适'],['heart','❤️','特别喜欢']]){const b=el('button','reaction');b.type='button';b.dataset.item=item.id;b.dataset.reaction=type;b.setAttribute('aria-label',`${label}：${item.title}`);b.setAttribute('aria-pressed','false');b.append(el('span','',icon),el('span','count','—'));b.addEventListener('click',async()=>{const current=feedback.items[item.id]?.mine||{};const value=!current[type];row.querySelectorAll('button').forEach(n=>n.disabled=true);try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,reaction:type,value})});if(!r.ok)throw new Error(r.status===429?'稍微慢一点，过一会儿再试。':'暂时没有记上，请稍后重试。');const result=await r.json();feedback.items[item.id]=result;paint();toast(value?'收到了，已记入匿名反馈。':'已撤回这条反馈。');}catch(e){toast(e.message);}finally{row.querySelectorAll('button').forEach(n=>n.disabled=false);}});row.append(b);}return row;}
function paint(){document.querySelectorAll('.reaction').forEach(b=>{const data=feedback.items[b.dataset.item];b.querySelector('.count').textContent=data?String(data.counts[b.dataset.reaction]||0):'—';b.setAttribute('aria-pressed',String(!!data?.mine?.[b.dataset.reaction]));});}
async function refresh(){try{const r=await fetch('/api/feedback',{cache:'no-store'});if(!r.ok)throw Error();feedback=await r.json();paint();document.querySelectorAll('.feedback-note').forEach(n=>n.textContent='匿名反馈 · 再点一次可撤回 · 点赞与点踩互斥');}catch{document.querySelectorAll('.feedback-note').forEach(n=>n.textContent='暂时无法读取反馈计数，请稍后重试。');}}
function readEdition(e){const wrap=el('div','reading');wrap.append(link('← 回到'+kinds[e.kind],`#${e.kind}`,'back'),el('p','eyebrow',e.sample?'STRUCTURE PREVIEW':`${e.date} · ${kinds[e.kind]}`),el('h2','',e.title),el('p','intro',e.intro));if(e.note)wrap.append(el('p','section-subtitle',e.note));if(e.sample)wrap.append(el('div','sample-banner','版式示例 · 以下不是实际新闻或选曲，反馈仅用于示例。'));const toc=el('nav','toc');toc.setAttribute('aria-label','本期目录');const ol=el('ol');e.items.forEach(item=>{const li=el('li');const a=link(item.title,`#edition/${e.id}`);a.addEventListener('click',ev=>{ev.preventDefault();document.getElementById(item.id).scrollIntoView({behavior:'smooth'});});li.append(a);ol.append(li);});toc.append(ol);wrap.append(toc);e.items.forEach((item,i)=>{const article=el('article','article');article.id=item.id;article.append(el('div','article-kicker',`${String(i+1).padStart(2,'0')} / ${item.category||kinds[e.kind]}`),el('h3','',item.title));if(item.artist)article.append(el('p','artist',`${item.artist} · ${item.album||''}`));if(item.releaseDate)article.append(el('p','edition-meta',`发行 ${item.releaseDate}${item.durationMs?' · '+Math.floor(item.durationMs/60000)+':'+String(Math.floor(item.durationMs/1000)%60).padStart(2,'0'):''}`));const prose=el('div','prose');item.body.forEach(block=>{if(block.heading)prose.append(el('h4','',block.heading));prose.append(el('p','',block.text));});article.append(prose);if(item.takeaway)article.append(el('div','takeaway','Mandy 的判断 · '+item.takeaway));const sources=el('div','sources');(item.sources||[]).forEach(source=>{const url=safeURL(source.url);if(url){const a=link(source.label+' ↗',url);a.target='_blank';a.rel='noopener noreferrer';sources.append(a);}});article.append(sources,reactionGroup(item),el('p','feedback-note','正在读取匿名反馈…'));wrap.append(article);});return wrap;}
function render(){if(!catalog)return;const path=location.hash.slice(1)||'home';const view=$('#view');view.replaceChildren();const isHome=path==='home';$('#hero').hidden=!isHome;$('#desk').hidden=!isHome;document.querySelectorAll('[data-nav]').forEach(a=>{a.removeAttribute('aria-current');if(path===a.dataset.nav)a.setAttribute('aria-current','page');});if(path.startsWith('edition/')){const e=[...catalog.editions,...catalog.examples].find(x=>x.id===path.slice(8));view.append(e?readEdition(e):heading('这页还没有找到','可以从往期归档重新打开。'));document.title=e?`${e.title} · Dots`:'找不到这一页 · Dots';}else if(path==='privacy'){view.append(privacy());document.title='关于与隐私 · Dots';}else if(path==='archive'){view.append(heading('往期归档','好内容不必赶着读，留在这里，慢慢翻。'));const input=el('input','search');input.type='search';input.placeholder='搜索标题、作者或曲目';input.setAttribute('aria-label','搜索归档');input.value=search;const filters=el('div','filters');const results=el('div');const update=()=>{const entries=catalog.editions.filter(e=>(activeFilter==='all'||e.kind===activeFilter)&&JSON.stringify(e).toLowerCase().includes(search.toLowerCase()));results.replaceChildren(entries.length?editionList(entries):el('p','section-subtitle','没有找到这一页，换个词试试。'));};input.addEventListener('input',()=>{search=input.value;update();});for(const [key,label] of [['all','全部'],['hn','每日精读'],['music','每周歌单']]){const b=el('button','filter',label);b.setAttribute('aria-pressed',String(activeFilter===key));b.addEventListener('click',()=>{activeFilter=key;filters.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));update();});filters.append(b);}view.append(input,filters,results);update();document.title='往期归档 · Dots';}else{const kind=path==='music'?'music':path==='hn'?'hn':null;const entries=catalog.editions.filter(e=>!kind||e.kind===kind);view.append(heading(kind?kinds[kind]:'最近留在这里的',kind==='music'?'以华语为主，也给陌生的声音留一个位置。':kind==='hn'?'十个阅读入口，保留证据、争议与自己的判断。':'读一篇，听一首。合上页面之后，还有一点回响。'));view.append(entries.length?editionList(entries):empty(kind||'hn'));document.title=kind?`${kinds[kind]} · Dots`:'Dots · Mandy 的云朵书桌';}refresh();}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});fetch('/content/index.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{catalog=data;render();}).catch(()=>{$('#view').replaceChildren(heading('书桌暂时没打开','请刷新页面重试，内容仍会保留在这里。'));});setInterval(()=>{if(!document.hidden)refresh();},30000);
