import {FeedbackState} from './feedback-state.mjs';
import {safeArtwork} from './media.mjs';
// 所有内容用 textContent 装配；外部 URL 仅允许 HTTPS，不执行内容中的 HTML。
let catalog; const feedback=new FeedbackState(); let activeFilter='all'; let search=''; let timer;
const $=s=>document.querySelector(s);
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function link(text,href,cls){const a=el('a',cls,text);a.href=href;return a;}
function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:null;}catch{return null;}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
const kinds={hn:'每日精读',music:'每周歌单'};
function heading(title,sub){const wrap=el('div');const h=el('div','view-heading');h.append(el('h2','',title));wrap.append(h);if(sub)wrap.append(el('p','section-subtitle',sub));return wrap;}
function editionList(editions){const wrap=el('div','edition-list');for(const e of editions){const a=link('',`#edition/${e.id}`,'edition-link');a.append(el('span','edition-kind',e.kind==='hn'?'↗':'♫'));const copy=el('div');copy.append(el('p','edition-meta',`${e.date} · ${kinds[e.kind]} · ${e.items.length} ${e.kind==='hn'?'篇':'首'}`),el('h3','',e.title));a.append(copy,el('span','arrow','↗'));wrap.append(a);}return wrap;}
function empty(kind){const box=el('div','empty');const img=el('img');img.src='/mandy.svg';img.alt='';const text=el('div');text.append(el('h3','',kind==='music'?'下一首好歌，还在路上。':'新的书签，还在整理。'),el('p','',kind==='music'?'正式歌单会出现在这里。每周日香港时间 19:00 左右，计划更新。':'正式精读会出现在这里。每日香港时间 10:00，计划更新。'));text.append(link('先看看内容会长什么样 →',`#edition/sample-${kind}`,'sample-link'));box.append(img,text);return box;}
function privacy(){const box=el('div','reading');box.append(heading('关于这张云朵书桌','Dots 是 Mandy 整理公开阅读与音乐发现的地方。'));for(const [h,t] of [['内容与来源','精读保留来源、日期、正文与判断边界。歌单保留曲名、艺人、版本、推荐理由与官方链接。这里不发布个人完整音乐库、原始听歌记录、账户信息或内部笔记。'],['匿名反馈','点击反馈后，本浏览器会保存一个仅本站使用、90 天有效的随机匿名 Cookie，用来避免同一浏览器重复计票。点赞和点踩互斥，爱心可以单独选择，再点一次可撤回。它不验证身份，也不能阻止清理 Cookie 或换设备重复投票。'],['存储与防刷','服务器保存随机浏览器标识、条目编号、选择和最后更新时间，不存姓名、邮箱、原始 IP 或自由文本。网络地址仅用于内存中的短时限流。Cloudflare 和现有服务器访问日志仍按基础设施原有策略处理。公开接口只提供条目汇总，不公开浏览器标识或个人投票明细。'],['反馈如何被看见','反馈提交成功后立即持久化并更新计数；可见页面约每 30 秒刷新一次公共计数。它不会自动唤醒助手。后续整理时可读取累计反馈，但匿名热度不会被当成你的个人偏好。'],['不想保留反馈？','重新打开对应条目，点击已选反馈即可撤回。清理 Cookie 只移除浏览器识别，不能撤回此前服务器上的匿名选择。本站不做跨站身份关联。']]){box.append(el('h3','',h),el('p','prose',t));}return box;}
const iconPaths={up:'M7 21H3V10h4m0 0 5-7c1-1 3 0 2.5 2L14 9h5a2 2 0 0 1 2 2l-1 7a3 3 0 0 1-3 3H7V10Z',down:'M7 3H3v11h4m0 0 5 7c1 1 3 0 2.5-2L14 15h5a2 2 0 0 0 2-2l-1-7a3 3 0 0 0-3-3H7v11Z',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z'};
function reactionGroup(item){
 const row=el('div','reactions feedback-control');row.setAttribute('role','group');row.setAttribute('aria-label',`对“${item.title}”的反馈`);
 for(const [type,label] of [['up','喜欢'],['down','不合适'],['heart','珍藏']]){
  const b=el('button','reaction');b.type='button';b.dataset.item=item.id;b.dataset.reaction=type;b.title=label;b.setAttribute('aria-label',`${label}：${item.title}`);b.setAttribute('aria-pressed','false');
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',iconPaths[type]);svg.append(path);b.append(svg,el('span','count','—'));
  b.addEventListener('click',async()=>{
   const request=feedback.begin(item.id,type);if(!request)return;paint();
   try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request),signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(r.status===429?'稍微慢一点，过一会儿再试。':'暂时没有记上，请稍后重试。');feedback.complete(item.id,await r.json());toast(request.value?'已保存。':'已撤回。');}
   catch(e){feedback.rollback(item.id);toast((e instanceof TypeError||e.name==='TimeoutError')?'连接中断，未确认保存，请重试。':e.message);}finally{paint();}
  });row.append(b);
 }return row;
}
function paint(){document.querySelectorAll('.reaction').forEach(b=>{
 const data=feedback.data.items[b.dataset.item], count=b.querySelector('.count'), next=data?String(data.counts[b.dataset.reaction]||0):'—', pressed=String(!!data?.mine?.[b.dataset.reaction]);
 if(count.textContent!==next){count.textContent=next;count.classList.remove('count-changed');void count.offsetWidth;count.classList.add('count-changed');}
 if(b.getAttribute('aria-pressed')!==pressed){b.classList.remove('reaction-changed');void b.offsetWidth;b.classList.add('reaction-changed');}
 b.setAttribute('aria-pressed',pressed);const pending=feedback.pending.has(b.dataset.item);b.disabled=pending||!data;b.setAttribute('aria-busy',String(pending));
});}
async function refresh(){const token=feedback.readToken();try{const r=await fetch('/api/feedback',{cache:'no-store'});if(!r.ok)throw Error();if(feedback.applySnapshot(await r.json(),token))paint();}catch{if(!Object.keys(feedback.data.items).length){paint();toast('暂时无法读取反馈计数，请稍后重试。');}}}
function trackCard(item,i){
 const card=el('article','record-card');card.id=item.id;const details=el('details','record-details'), summary=el('summary','record-front');
 const art=el('span','record-art');art.setAttribute('aria-hidden','true');const vinyl=el('span','vinyl');vinyl.append(el('span','vinyl-label','dots'));const sleeve=el('span','record-sleeve');const fallback=el('span','cover-fallback',item.artist?.slice(0,2)||'♫');sleeve.append(fallback);
 const src=safeArtwork(item.artwork);if(src){const img=el('img');img.src=src;img.alt='';img.loading='lazy';img.decoding='async';img.referrerPolicy='no-referrer';img.addEventListener('error',()=>img.remove(),{once:true});sleeve.append(img);}art.append(vinyl,sleeve);
 const copy=el('span','record-copy');copy.append(el('span','record-number',`${String(i+1).padStart(2,'0')} / ${item.category==='本期重点'?'精选':'SIDE B'}`),el('span','record-title',item.title),el('span','record-artist',item.artist||''),el('span','record-open','＋ 曲目笔记'));summary.append(art,copy);details.append(summary);
 const notes=el('div','record-notes');notes.append(el('p','track-album',`${item.album||''} · ${item.releaseDate||''}`));for(const block of item.body){if(block.heading)notes.append(el('h4','',block.heading));notes.append(el('p','',block.text));}if(item.takeaway)notes.append(el('p','',item.takeaway));details.append(notes);card.append(details);
 const controls=el('div','record-controls'), source=item.sources[0];if(source&&safeURL(source.url)){const a=link('Apple Music ↗',source.url,'listen-link');a.target='_blank';a.rel='noopener noreferrer';controls.append(a);}controls.append(reactionGroup(item));card.append(controls);return card;
}
function readEdition(e){const wrap=el('div','reading');wrap.append(link('← 回到'+kinds[e.kind],`#${e.kind}`,'back'),el('p','eyebrow',e.sample?'STRUCTURE PREVIEW':`${e.date} · ${kinds[e.kind]}`),el('h2','',e.title),el('p','intro',e.intro));if(e.note)wrap.append(el('p','section-subtitle',e.note));if(e.sample)wrap.append(el('div','sample-banner','版式示例 · 以下不是实际新闻或选曲，反馈仅用于示例。'));const toc=el('nav','toc');toc.setAttribute('aria-label','本期目录');const ol=el('ol');e.items.forEach(item=>{const li=el('li');const a=link(item.title,`#edition/${e.id}`);a.addEventListener('click',ev=>{ev.preventDefault();document.getElementById(item.id).scrollIntoView({behavior:'smooth'});});li.append(a);ol.append(li);});toc.append(ol);wrap.append(toc);e.items.forEach((item,i)=>{if(e.kind==='music'){wrap.append(trackCard(item,i));return;}const article=el('article','article');article.id=item.id;article.append(el('div','article-kicker',`${String(i+1).padStart(2,'0')} / ${item.category||kinds[e.kind]}`),el('h3','',item.title));if(item.artist)article.append(el('p','artist',`${item.artist} · ${item.album||''}`));if(item.releaseDate)article.append(el('p','edition-meta',`发行 ${item.releaseDate}${item.durationMs?' · '+Math.floor(item.durationMs/60000)+':'+String(Math.floor(item.durationMs/1000)%60).padStart(2,'0'):''}`));const prose=el('div','prose');item.body.forEach(block=>{if(block.heading)prose.append(el('h4','',block.heading));prose.append(el('p','',block.text));});article.append(prose);if(item.takeaway)article.append(el('div','takeaway','Mandy 的判断 · '+item.takeaway));const sources=el('div','sources');(item.sources||[]).forEach(source=>{const url=safeURL(source.url);if(url){const a=link(source.label+' ↗',url);a.target='_blank';a.rel='noopener noreferrer';sources.append(a);}});article.append(sources,reactionGroup(item));wrap.append(article);});return wrap;}
function homeView(){
 const outer=el('div','daily-home');const title=el('div','daily-heading');const titleText=el('div');titleText.append(el('p','eyebrow','MANDY’S DAILY NOTES'),el('h1','','今天的阅读与声音'));title.append(titleText);outer.append(title);
 const columns=el('div','daily-columns');const news=el('section','news-feed');const music=el('aside','music-feed');music.setAttribute('aria-label','最新歌单');const latestHN=catalog.editions.find(e=>e.kind==='hn');const latestMusic=catalog.editions.find(e=>e.kind==='music');
 if(latestHN){const h=el('div','feed-heading');h.append(el('h2','','每日精读'),link(latestHN.date+' · 10 篇 →',`#edition/${latestHN.id}`,'feed-date'));news.append(h,el('p','feed-intro',latestHN.intro));latestHN.items.forEach((item,i)=>{const card=el('article','news-item');card.append(el('p','item-meta',`${String(i+1).padStart(2,'0')} · ${item.category}`),el('h3','',item.title),el('p','news-summary',item.preview||item.body[0].text));const more=el('details','read-more');more.append(el('summary','','展开争议、边界与判断'));const prose=el('div','prose');for(const block of (item.preview&&item.preview!==item.body[0].text?item.body:item.body.slice(1))){if(block.heading)prose.append(el('h4','',block.heading));prose.append(el('p','',block.text));}if(item.takeaway)prose.append(el('div','takeaway','Mandy 的判断 · '+item.takeaway));more.append(prose);card.append(more);const sources=el('div','sources');for(const source of item.sources){const url=safeURL(source.url);if(url){const a=link(source.label+' ↗',url);a.target='_blank';a.rel='noopener noreferrer';sources.append(a);}}card.append(sources,reactionGroup(item));news.append(card);});news.append(el('p','reading-boundary',latestHN.note));}else news.append(empty('hn'));
 if(latestMusic){const h=el('div','feed-heading');h.append(el('h2','','本周歌单'),link(latestMusic.date+' →',`#edition/${latestMusic.id}`,'feed-date'));music.append(h,el('p','feed-intro',latestMusic.intro));latestMusic.items.forEach((item,i)=>music.append(trackCard(item,i)));}else music.append(empty('music'));
 columns.append(news,music);outer.append(columns);return outer;
}
function render(){if(!catalog)return;const path=location.hash.slice(1)||'home';const view=$('#view');view.replaceChildren();const isHome=path==='home';$('#hero').hidden=true;$('#desk').hidden=true;document.querySelectorAll('[data-nav]').forEach(a=>{a.removeAttribute('aria-current');if(path===a.dataset.nav)a.setAttribute('aria-current','page');});if(path.startsWith('edition/')){const e=[...catalog.editions,...catalog.examples].find(x=>x.id===path.slice(8));view.append(e?readEdition(e):heading('这页还没有找到','可以从往期归档重新打开。'));document.title=e?`${e.title} · Dots`:'找不到这一页 · Dots';}else if(isHome){view.append(homeView());document.title='Dots · Mandy 的云朵书桌';}else if(path==='privacy'){view.append(privacy());document.title='关于与隐私 · Dots';}else if(path==='archive'){view.append(heading('往期归档','好内容不必赶着读，留在这里，慢慢翻。'));const input=el('input','search');input.type='search';input.placeholder='搜索标题、作者或曲目';input.setAttribute('aria-label','搜索归档');input.value=search;const filters=el('div','filters');const results=el('div');const update=()=>{const entries=catalog.editions.filter(e=>(activeFilter==='all'||e.kind===activeFilter)&&JSON.stringify(e).toLowerCase().includes(search.toLowerCase()));results.replaceChildren(entries.length?editionList(entries):el('p','section-subtitle','没有找到这一页，换个词试试。'));};input.addEventListener('input',()=>{search=input.value;update();});for(const [key,label] of [['all','全部'],['hn','每日精读'],['music','每周歌单']]){const b=el('button','filter',label);b.setAttribute('aria-pressed',String(activeFilter===key));b.addEventListener('click',()=>{activeFilter=key;filters.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));update();});filters.append(b);}view.append(input,filters,results);update();document.title='往期归档 · Dots';}else{const kind=path==='music'?'music':path==='hn'?'hn':null;const entries=catalog.editions.filter(e=>!kind||e.kind===kind);view.append(heading(kind?kinds[kind]:'最近留在这里的',kind==='music'?'以华语为主，也给陌生的声音留一个位置。':kind==='hn'?'十个阅读入口，保留证据、争议与自己的判断。':'读一篇，听一首。合上页面之后，还有一点回响。'));view.append(entries.length?editionList(entries):empty(kind||'hn'));document.title=kind?`${kinds[kind]} · Dots`:'Dots · Mandy 的云朵书桌';}paint();refresh();}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});fetch('/content/index.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{catalog=data;render();}).catch(()=>{$('#view').replaceChildren(heading('书桌暂时没打开','请刷新页面重试，内容仍会保留在这里。'));});setInterval(()=>{if(!document.hidden)refresh();},30000);

// 跳过导航只移动焦点，不把正文锚点当作内容路由。
document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();document.getElementById('content').focus();document.getElementById('content').scrollIntoView();});
